# Generated by Django 5.0.3 on 2024-04-23 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_location_category_alter_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location_category',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='items.location_category'),
            preserve_default=False,
        ),
    ]
